SUPABASE_SCHEMA_ID_BIGQUERY = "bigquery"
SUPABASE_SCHEMA_ID_RAW = "raw"
SUPABASE_SCHEMA_ID_PUBLIC = "public"
SUPABASE_TABLE_ID_BOARD = "board"
SUPABASE_TABLE_ID_PIN = "pin"
SUPABASE_TABLE_ID_PIN_VECTOR = "pin_vector"

SUPABASE_BATCH_SIZE = 1000

SUPABASE_RPC_ID_GET_PINS = "get_pins"
SUPABASE_RPC_ID_GET_PIN_VECTORS = "get_pin_vectors"
SUPABASE_RPC_ID_GET_DISTINCT_USERS = "get_distinct_users"
SUPABASE_RPC_ID_GET_DISTINCT_USERS_STRICT = "get_distinct_users_strict"

DEFAULT_RECOMMEND_BOARD_NAME = "Recommandé pour toi"
DEFAULT_RECOMMEND_BOARD_DESCRIPTION = (
    "Les pins des autres utilisateurs qui pourraient te plaire"
)
