name: Embed from Pinterest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  embed-from-pinterest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.embed
        push: false
        load: true
        tags: pin-graph:embed
        
    - name: Run Pinterest embedding process
      env:
        SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
      run: |
        docker run --rm \
          -e SECRETS_JSON="$SECRETS_JSON" \
          pin-graph:embed \
          --from-pinterest true 