name: Raw To Public

on:
  workflow_dispatch:

jobs:
  insert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.insert
          push: false
          load: true
          tags: pin-graph-insert:latest

      - name: Run insert process
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
        run: |
          docker run --rm \
            -e SECRETS_JSON="$SECRETS_JSON" \
            pin-graph-insert:latest 